### ISSUE TITLE
GooglePlayStoreApi.ForbiddenException: Error=BadAuthentication

### ISSUE THREAD

**Issue by 89z** [kagasu/GooglePlayStoreApi#13]
Using this program:

~~~cs
using GooglePlayStoreApi;
var email = "srpen6@gmail.com";
var androidId = "53f0bd646b2f1f3b";
var token = "oauth2_4/0AX4XfWj0VLQ7sotWBO5jQng51SFjoge5bFRWN5ta01qt_80YrVRjk...";
var client = new GooglePlayStoreClient(email, androidId);
await client.GetGoogleToken(token);
~~~

I get this result:

~~~
Unhandled exception. GooglePlayStoreApi.ForbiddenException: Error=BadAuthentication
   at GooglePlayStoreApi.GooglePlayStoreClient.GetGoogleToken(String token)
   at <Program>$.<<Main>$>d__0.MoveNext() in C:\play\Program.cs:line 11
--- End of stack trace from previous location ---
   at <Program>$.<Main>(String[] args)
~~~

**Comment by kagasu** [comment]
I just tested the same program.
There is no error.
So the problem is your side i think.
Re-generate token(`oauth2_4/...`)and try again.

**Comment by 89z** [comment]
Nope. Using this program:

~~~cs
using GooglePlayStoreApi;
using System;
var email = "srpen6@gmail.com";
var androidId = "53f0bd646b2f1f3b";
var token = "oauth2_4/0AX4XfWjG7z6eLP4Hvp0avZ54JfhRDhl324ghOvpZ4Pl_4Q9ZWuYb5...";
var gmailPackageName = "com.google.android.gm";
var client = new GooglePlayStoreClient(email, androidId);
token = await client.GetGoogleToken(token);
Console.WriteLine(token);
await client.GetGoogleAuth(token);
var appDetail = await client.AppDetail(gmailPackageName);
var appName = appDetail.Item.Title;
Console.WriteLine(appName);
~~~

I get this result:

~~~
aas_et/AKppINZ2ZKE3HB9iHh3j8PoHQdDU5Ig5nQ8vm-VOqkP5EHuTlAf3IqONxkXAFnuVS9HNiWP...

Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GooglePlayStoreApi.GooglePlayStoreClient.Get(String url)
   at GooglePlayStoreApi.GooglePlayStoreClient.AppDetail(String packageName)
   at <Program>$.<<Main>$>d__0.MoveNext() in D:\Desktop\play\Program.cs:line 11
--- End of stack trace from previous location ---
   at <Program>$.<Main>(String[] args)
~~~

**Comment by kagasu** [comment]
Your program is works well with my Android ID.

Your `androidId` is invalid.
Follow the steps below

1. Install DeviceID
https://play.google.com/store/apps/details?id=com.evozi.deviceid
2. Check your real DeviceID
![image](https://user-images.githubusercontent.com/1202244/131213061-843d2092-9b63-41f7-a158-53aac09a4c5a.png)

**Comment by 89z** [comment]
Its the same:

> ![Untitled](https://user-images.githubusercontent.com/73562167/131221913-926f6da5-62ed-4296-8adc-06a703a0ac69.png)

**Comment by 89z** [comment]
This program works:

~~~cs
using GooglePlayStoreApi;
using System;
var email = "srpen6@gmail.com";
var androidId = "38B5418D8683ADBB";
var client = new GooglePlayStoreClient(email, androidId);

// var token = "oauth2_4/0AX4XfWg6cBIkLf1VxJDfc8f9Ov5Uvq7-Mul4HXPYf4MOVWynwF...";
// token = await client.GetGoogleToken(token);
var token = "aas_et/AKppINa2pC3kcYogrIaBtjAXLN0JAspvdet0MMGRjYWlvRqUWo8YtQFS...";

await client.GetGoogleAuth(token);
var appDetail = await client.AppDetail("com.google.android.youtube");
Console.WriteLine(appDetail.Item.Details);
~~~

The problem is that `androidId` must be the "Google Service Framework", not "Android Device ID". Also the device being used, must have at least Android API 25.
